
name: 'dbt_demo'

profile: 'dbt_demo'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  dbt_demo:
    # Config indicated by + and applies to all files under models/example/
    staging:
      database: stg
      schema: airbnb
      +materialized: table
